fid = fopen('het_userdata.txt','w');

fprintf(fid,...
[...
'/*\n'...
' *  odefun.c\n'...
' *  cvode_test\n'...
' *\n'...
' *  Created by Andrew Matteson on 1/31/11.\n'...
' *  Copyright 2011 __MyCompanyName__. All rights reserved.\n'...
' *\n'...
' */\n'...
'\n'...
'/*#include <stdio.h>*/\n'...
'#include <stdlib.h>\n'...
'#include <string.h>\n'...
'\n'...
'\n'...
'/* Header files with a description of contents used */\n'...
'\n'...
'#include <cvode/cvode.h>             /* prototypes for CVODE fcts., consts. */\n'...
'#include <cvode/cvode_spgmr.h>        /* prototypes & constants for CVSPGMR */\n'...
'#include <nvector/nvector_serial.h>  /* serial N_Vector types, fcts., macros */\n'...
'/*#include <cvode/cvode_dense.h> */      /* prototype for CVDense */\n'...
'/*#include <sundials/sundials_dense.h>*/ /* definitions DlsMat DENSE_ELEM */\n'...
'#include <sundials/sundials_types.h> /* definition of type realtype */\n'...
'#include "UserMacros.c"\n'...
'\n'...
'\n'...
'#define NEQ '	num2str(length(m1.species)) '      /* number of equations  */\n'...
'#define NUMOUT '  num2str(numout) '\n'...
'#define NUMPARAM ' num2str(length(m1.parameters)) '\n'...
'\n'...
'typedef struct {\n'...
]...
);

fprintf(fid,...
	['realtype spJ[' num2str(length(m1.species)^2 - sum(sum(cellfun(@(x) strcmp('',x),jac_cell)))) '];\n'...
	'N_Vector J_diag;\n\n']...
    );

for iter = 1:length(m1.parameters)
    fprintf(fid,['realtype ' m1.parameters(iter).name ';\n']);
end

fprintf(fid,'\n} UserData;\n\n');

fclose(fid);

%%

fid = fopen('het_parampass.txt','w');

fprintf(fid, 'static void parampass(UserData* data, realtype param[])\n{\n');

for iter = 1:length(m1.parameters)
    fprintf(fid,['data->' m1.parameters(iter).name ' = param[' num2str(iter-1) '];\n']);
end

fprintf(fid, '}\n\n');